config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('login/', include('login.urls')),
    path('tareas/', include('tasks.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

login/urls.py
from django.urls import path
from .views import *

app_name = 'login'

urlpatterns = [
    path('', SignInView.as_view(), name='loginProfile'),
    path('register', RegisterProfile.as_view(), name='newProfile'),
    path('finish', SecondDataProfile.as_view(), name='dataProfile'),
    path('logout', SignOutView.as_view(), name='logOutProfile'),
    
]

tasks/urls.py
from django.urls import path
from .views import *

app_name = 'task'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('importantes', TasksImportants.as_view(), name='important'),
    path('basicas', TasksPending.as_view(), name='basic'),
    path('pospuestas', TasksPostponed.as_view(), name='postponed'),
    path('incompletas', TasksIncomplete.as_view(), name='incomplete'),
    path('nueva', NewTask.as_view(), name='new')
    
]

tasks/models.py
import os
import uuid
from django.db import models
from PIL import Image #type:ignore

from user_profile.models import User

def get_image_path(instance, filename):
    # Genera un UID único
    uid = uuid.uuid4()
    # Obtiene la extensión original del archivo
    extension = os.path.splitext(filename)[1]
    # Define la nueva ruta del archivo de la imagen con el UID como nombre y la extensión original
    new_filename = f'tasks_images/{uid}{extension}'
    return new_filename

class Task(models.Model):
    name = models.CharField(max_length=50, verbose_name='Nombre de la tarea')
    date_register = models.DateTimeField(verbose_name='Fecha registro', auto_now_add=True)
    date_limit = models.DateTimeField(verbose_name='Fecha limite')
    times_postponed = models.IntegerField(verbose_name='Veces pospuesta')
    task_priority = models.CharField(verbose_name='Prioridad de la tarea', max_length=50)
    user = models.ForeignKey(User, verbose_name='Usuario', on_delete=models.CASCADE)
    task_image = models.ImageField(verbose_name="Imagen de la tarea (Opcional)", upload_to=get_image_path, blank=True)
    task_description = models.TextField(verbose_name='Descripcion de la tarea')

    class Meta:
        db_table = "task"
        managed = True
        verbose_name = "task"
        verbose_name_plural = "tasks"
        ordering = ["id"]

user_profile/models.py
import os
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image #type:ignore

# Se hereda de la base del modelo usuario, reescribiendo el modelo que tiene por defecto
# django

def get_image_path(instance, filename):
    # Genera un UID único
    uid = uuid.uuid4()
    # Obtiene la extensión original del archivo
    extension = os.path.splitext(filename)[1]
    # Define la nueva ruta del archivo de la imagen con el UID como nombre y la extensión original
    new_filename = f'profile_img/{uid}{extension}'
    return new_filename


class User(AbstractUser):
    image = models.ImageField(verbose_name="Imagen de perfil", upload_to=get_image_path, blank=True)
    nick = models.CharField(verbose_name="Apodo", max_length=50, blank=True)
    bio = models.TextField(verbose_name="Descripcion o motivos de registro", blank=True)

    class Meta:
        db_table = "user"
        managed = True
        verbose_name = "user"
        verbose_name_plural = "users"
        ordering = ["id"]

    def __str__(self):
        return self.username
    
    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        if self.image:
            image = Image.open(self.image.path)
            max_size = (400, 400)
            image.thumbnail(max_size, Image.LANCZOS)
            image.save(self.image.path, quality=10, optimize=True)

login/forms.py
from django import forms
from user_profile.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(max_length=65, label="Nombre de usuario")
    password = forms.CharField(max_length=65, widget=forms.PasswordInput, label="Contraseña")

class RegisterProfileForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class SecondStepRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'image', 'nick', 'bio']

        # Se reemplaza el TextArea por un campo de texto normal
        widgets = {
            'bio': forms.TextInput(),
        }

tasks/forms.py
from django.forms import ModelForm

from tasks.models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'date_limit', 'task_priority', 'task_image', 'task_description']
        

home/views.py
from django.views.generic import TemplateView

from functions.mixins import ValidateUserDataRegister

class HomeView(ValidateUserDataRegister, TemplateView):
    template_name = 'welcome.html'

login/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import authenticate, login
from django.views.generic import CreateView, UpdateView

from functions.mixins import ContextMixin, IsUserAunthenticated, RestrictSecondPageRegister
from .forms import RegisterProfileForm, SecondStepRegisterForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin



# Vista de Inicio de Sesion
class SignInView(ContextMixin, LoginView):
    template_name = 'login.html'
    redirect_authenticated_user = True
    custom_context = {
        'app_name': 'Iniciar Sesion'
    }

class SignOutView(LoginRequiredMixin, LogoutView):
    pass

class RegisterProfile(IsUserAunthenticated, ContextMixin, CreateView):
    form_class = RegisterProfileForm
    success_url = reverse_lazy('login:dataProfile')
    template_name = 'register.html'
    custom_context = {
        'app_name': 'Registrar nuevo usuario'
    }
    
    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return response


class SecondDataProfile(LoginRequiredMixin, RestrictSecondPageRegister, ContextMixin, UpdateView):
    form_class = SecondStepRegisterForm
    template_name = "data_profile.html"

    success_url = reverse_lazy('login:dataProfile')

    custom_context = {
        'app_name': 'Finalizar registro de perfil',
        'title_container': 'Ultimos ajustes a tu perfil 👷'
    }

    def get_object(self):
        return self.request.user

tasks/views.py
from random import randint
from django.views.generic import TemplateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from functions.mixins import ContextMixin, ValidateUserDataRegister
from tasks.forms import TaskForm

class HomeView(LoginRequiredMixin, ValidateUserDataRegister, ContextMixin, TemplateView):
    template_name = 'home.html'
    custom_context = {
        'app_name': 'Mis tareas',
        'range_for': range(1, randint(1, 11))
    }

class NewTask(LoginRequiredMixin, ValidateUserDataRegister, ContextMixin, CreateView):
    template_name = 'new_task.html'
    form_class = TaskForm

    custom_context = {
        'app_name': 'Nueva tarea',
        'range_for': range(1, randint(1, 11))
    }

class TasksImportants(LoginRequiredMixin, ValidateUserDataRegister, ContextMixin, TemplateView):
    template_name = 'task_important.html'
    custom_context = {
        'app_name': 'Tareas importantes',
        'range_for': range(1, randint(1, 11))
    }

class TasksPending(LoginRequiredMixin, ValidateUserDataRegister, ContextMixin, TemplateView):
    template_name = 'task_basic.html'
    custom_context = {
        'app_name': 'Tareas basicas',
        'range_for': range(1, randint(1, 11))
    }

class TasksPostponed(LoginRequiredMixin, ValidateUserDataRegister, ContextMixin, TemplateView):
    template_name = 'task_postponed.html'
    custom_context = {
        'app_name': 'Tareas pospuestas',
        'range_for': range(1, randint(1, 11))
    }

class TasksIncomplete(LoginRequiredMixin, ValidateUserDataRegister, ContextMixin, TemplateView):
    template_name = 'task_incomplete.html'
    custom_context = {
        'app_name': 'Tareas incompletas',
        'range_for': range(1, randint(1, 11))
    }

home/templates/welcome.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Icon Page -->
        <link rel="icon" type="image/x-icon" href="{% static 'ico/favicon.ico' %}" />
            
        <!-- Core Bootstrap -->
        <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">

        <!-- Fonts  -->
        <link rel="stylesheet" href="{% static 'fonts/nunito/nunito.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/fontawesome/fontawesome.css' %}">

        <title>TaskDev</title>

        <!-- Custom Styles -->
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'css/page_welcome.css' %}">
    
    </head>
    <body class="d-flex h-100 text-center text-bg-dark">
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
            <header class="mb-auto">
                <div>
                    <h3 class="float-md-start mb-0 "><b>TaskDev <i class="fas fa-clipboard-list"></i></b></h3>
                    <nav class="nav nav-masthead justify-content-center float-md-end">
                        <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Pagina principal</a>
                        
                        {% if request.user.is_authenticated %}
                        <a class="nav-link fw-bold py-1 px-0" href="{% url 'task:home' %}">Task</a>
                        {% else %}
                        <a class="nav-link fw-bold py-1 px-0" href="{% url 'login:loginProfile' %}">Iniciar sesion</a>
                        <a class="nav-link fw-bold py-1 px-0" href="{% url 'login:newProfile' %}">Registrarme</a>
                        {% endif %}

                    </nav>
                </div>
            </header>

            <main class="px-1">
                <h1>Task Tool</h1>
                <p class="lead">¿Qué es Task Dev y cómo te puede ayudar? Task Dev es el proyecto personal de un joven venezolano apasionado por la informática, que busca ofrecer una solución práctica y sencilla para gestionar y administrar esas pequeñas tareas que a veces se nos olvidan por no ser tan importantes. Con Task Dev, podrás organizar tu día a día de forma eficiente y divertida, y disfrutar de las novedades que se irán añadiendo poco a poco. Este proyecto está hecho con mucho cariño y espero que te guste. Además, puedes acceder al código fuente en GitHub y ver cómo funciona por dentro.
                </p>
                <p class="h6">
                    Contactame <i class="fa-solid fa-turn-down"></i>
                </p>
                <p class="lead">
                    <a href="https://www.facebook.com/raicodev" class="text-white"><i class="fa-lg fa-brands fa-facebook"></i></a> &nbsp;
                    <a href="https://github.com/raicodev/taskdev" class="text-white"><i class="fa-lg fa-brands fa-github"></i></a> &nbsp;
                    <a href="https://www.tiktok.com/@raicodev" class="text-white"><i class="fab fa-tiktok"></i></a>
                    
                </p>
            </main>

            <footer class="mt-auto text-white-50">
                <p>By RaicoDev @<script> document.write(new Date().getFullYear()) </script></p>
            </footer>
        </div>
    </body>
</html>

login/templates/login.html
{% extends 'base_auth.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="authentication-wrapper authentication-basic container-p-y">
	<div class="authentication-inner">
		<!-- Login -->
		<div class="card">
			<div class="card-body">

				<!-- Logo -->
                <div class="app-brand justify-content-center">
                    <a href="{% url 'home:home' %}" class="app-brand-link gap-2">
                        <span class="app-brand-logo demo">
                            <img width="35" src="{% static 'ico/favicon.ico' %}" alt="logo">
                        </span>
                        <span class="app-brand-text demo text-body fw-bolder">TaskDev</span>
                    </a>
                </div>
                <!-- /Logo -->

                <!-- Title App-->
                <h4 class="mb-2">Inicio de sesion</h4>
                <p class="mb-4">Tu tiempo es un tesoro 💎… Así que, aprovechalo al maximo 🤘</p>
                <!-- End Title App-->

                {% for _, error_list in form.errors.items %}
                        {% for error in error_list %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                {{ error }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endfor %}


                <!-- Login Form -->
                <form action=""  class="mb-3" method="POST">
                    {% csrf_token %}
                    {% for field in form %}

                        <div class="mb-3 {% if field.label == 'Contraseña (confirmación)' or field.label == 'Contraseña' %} form-password-toggle {% endif %} ">
                            
                            {% if field.label == 'Contraseña'  %}
                            <div class="d-flex justify-content-between">
                                <label class="form-label">{{ field.label }}</label>
                                <a href="javascript:void(0)">
                                <small>¿Olvidaste tu contraseña?</small>
                                </a>
                            </div>
                            {% else %}
                                <label class="form-label">{{ field.label }}</label>
                            {% endif %}

                            <div class="input-group input-group-merge">
                                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                                {% if field.label == 'Contraseña (confirmación)' or field.label == 'Contraseña' %}
                                <span class="input-group-text cursor-pointer"><i class="fas fa-eye"></i></span>
                                {% endif %}
                                {% if field.help_text %}
                                <button type="button" class="btn btn-outline-primary btn-icon" data-bs-toggle="tooltip" data-bs-offset="0,4" 
                                data-bs-placement="top" data-bs-html="true" title=""
                                data-bs-original-title="{{ field.help_text }}">
                                    <i class="fas fa-question"></i>
                                </button>
                                {% endif %}
                              </div>
                        </div>
                    {% endfor %}
                    <div class="mb-3">
						<button class="btn btn-primary d-grid w-100" type="submit">Iniciar Sesion</button>
					</div>
                </form>
                <!-- End Login Form -->

                <!-- Message Register -->
                <p class="text-center">
					<span>¿No tienes cuenta?</span>
					<a href="{% url 'login:newProfile' %}">
					    <span>Registrarme</span>
					</a>
				</p>
                <!-- End Message Register -->
				
			</div>
		</div>
		<!-- /Login -->
	</div>
</div>
{% endblock %}
    

login/templates/register.html
{% extends 'base_auth.html' %}

{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="authentication-wrapper authentication-basic container-p-y">
    <div class="authentication-inner">
        <!-- Register Card -->
        <div class="card">
            <div class="card-body">
                <!-- Logo -->
                <div class="app-brand justify-content-center">
                    <a href="{% url 'home:home' %}" class="app-brand-link gap-2">
                        <span class="app-brand-logo demo">
                            <img width="35" src="{% static 'ico/favicon.ico' %}" alt="logo">
                        </span>
                        <span class="app-brand-text demo text-body fw-bolder">TaskDev</span>
                    </a>
                </div>
                <!-- /Logo -->

                <!-- Title App-->
                <h4 class="mb-2">Organízate con estilo. 😎</h4>
                <p class="mb-4">Registrarte representa la magia de planificar tu tiempo</p>
                <!-- End Title App-->

                <!-- Register Form -->
                <form action=""  class="mb-3" method="POST">
                    {% csrf_token %}
                    {% for field in form %}

                        <div class="mb-3 {% if field.label == 'Contraseña (confirmación)' or field.label == 'Contraseña' %} form-password-toggle {% endif %} ">
                            <label class="form-label">{{ field.label }}</label>
                            
                            {% if field.help_text or field.label == 'Contraseña (confirmación)' or field.label == 'Contraseña' %}
                                
                            <div class="input-group input-group-merge">
                                
                                {% if field.errors %}
                                {{ field|add_class:'form-control is-invalid'|attr:'autocomplete:off' }}
                                {% else %}
                                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                                {% endif %}
                                    
                                {% if field.label == 'Contraseña (confirmación)' or field.label == 'Contraseña' %}
                                    <span class="input-group-text cursor-pointer"><i class="fas fa-eye"></i></span>
                                {% endif %}
                                <button type="button" class="btn btn-outline-primary btn-icon" data-bs-toggle="tooltip" data-bs-offset="0,4" 
                                data-bs-placement="top" data-bs-html="true" title=""
                                data-bs-original-title="{{ field.help_text }}">
                                    <i class="fas fa-question"></i>
                                </button>
                                
                                {% if field.errors %}
                                <div class="invalid-feedback">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                                </div>
                                {% endif %}
                            </div>

                            {% else %}
                            {% if field.errors %}
                            {{ field|add_class:'form-control is-invalid'|attr:'autocomplete:off' }}
                            {% else %}
                            {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                            {% endif %}
                            {% if field.errors %}
                            <div class="invalid-feedback">
                            {% for error in field.errors %}
                                {{ error }}
                            {% endfor %}
                            </div>
                            {% endif %}
                            {% endif %}
                        </div>
                    {% endfor %}
                    
                    <button type="submit" class="btn btn-primary d-grid w-100">Registrarme</button>
                </form>
                <!-- End Register Form -->
                
                <p class="text-center">
                    <span>¿Ya tienes una cuenta?</span>
                    <a href="{% url 'login:loginProfile' %}">
                    <span>Inicia sesion</span>
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}
    

tasks/templates/task_basic.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="d-flex align-items-center justify-content-between pt-3">
    <h3>¡Hey, {{ user.first_name }}! Aqui estan tus tareas basicas. </h3>
    <a href="{% url 'task:home' %}" class="btn btn-info" >
		<i class="fas fa-angle-left d-block d-sm-none"></i>
        <span class="d-none d-sm-block"><i class="fas fa-angle-left"></i> Regresar a inicio</span>
    </a>
</div>

<div class="card bg-transparent shadow-none border-0 my-4" >
	<div class="card-body row p-0 pb-3">

		<div class="col-12 col-md-12 ">
			<div class="d-flex justify-content-between flex-wrap gap-3 me-5">

                <div class="d-flex align-items-center gap-3 me-4 me-sm-0">
					<span class=" bg-label-warning p-2 rounded">
                        <i class="fas fa-list"></i>
					</span>
					<div class="content-right">
						<p class="mb-0">Pendientes</p>
						<h4 class="text-warning mb-0">2</h4>
					</div>
				</div>

				<div class="d-flex align-items-center gap-3 me-4 me-sm-0">
					<span class=" bg-label-success p-2 rounded">
                        <i class="fas fa-check-double"></i>
					</span>
					<div class="content-right">
						<p class="mb-0">Completadas</p>
						<h4 class="text-success mb-0">2</h4>
					</div>
				</div>

				<div class="d-flex align-items-center gap-3">
					<span class="bg-label-info p-2 rounded">
                        <i class="fas fa-clock"></i>
					</span>
					<div class="content-right">
						<p class="mb-0">Pospuestas</p>
						<h4 class="text-info mb-0">5</h4>
					</div>
				</div>

				<div class="d-flex align-items-center gap-3">
					<span class="bg-label-danger p-2 rounded">
                        <i class="fas fa-times-circle"></i>
					</span>
					<div class="content-right">
						<p class="mb-0">Incompletas </p>
						<h4 class="text-danger mb-0">14</h4>
					</div>
				</div>

			</div>
		</div>
		
	</div>
</div>
<div class="card mb-4">
	<div class="card-body">
		<h5 class="card-title">Filtrado de tareas</h5>
		<div class="row">
			<div class="col-md">
				<div class="form-check form-check-inline mt-1">
					<input class="form-check-input" type="checkbox" id="tareas_pendientes" value="option1">
					<label class="form-check-label" for="tareas_pendientes"><i class="fas fa-exclamation-triangle text-danger"></i> Pendientes</label>
				</div>
                <div class="form-check form-check-inline mt-1">
					<input class="form-check-input" type="checkbox" id="tareas_pospuestas" value="option1">
                       
                        <label class="form-check-label" for="tareas_pospuestas"><i class="fas fa-clock text-info"></i> Pospuestas</label>
				</div>
                <div class="form-check form-check-inline mt-1">
					<input class="form-check-input" type="checkbox" id="tareas_completadas" value="option1">
                    <label class="form-check-label" for="tareas_completadas"> <i class="fas fa-check-double text-success"></i> Completadas</label>
				</div>
                <div class="form-check form-check-inline mt-1">
					<input class="form-check-input" type="checkbox" id="tareas_incompletas" value="option1">
                    <label class="form-check-label" for="tareas_incompletas"> <i class="far fa-calendar-times text-warning"></i> Incompletas</label>
				</div>
			</div>
		</div>
	</div>
</div>



<div class="row" data-masonry='{"percentPosition": true }'>
    <div class="col-md-6 col-xl-4 mb-4">
        <div class="card ">
            <div class="card-header flex-grow-0">
                <div class="d-flex">
                    <div class="d-flex w-100 flex-wrap align-items-center justify-content-between gap-1">
                        <div class="me-2">
                            <h5 class="mb-0">Estado: Pendiente <i class="fas fa-exclamation-triangle text-danger"></i></h5>
                            <small class="text-muted">Hasta: 07 Sep 2020 a las 10:30 AM</small>
                        </div>
                        <div class="dropdown d-none d-sm-block">
                            <button class="btn p-0" type="button" id="eventList" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-angle-double-down"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="eventList">
                                <a class="dropdown-item" href="javascript:void(0);">Last 28 Days</a>
                                <a class="dropdown-item" href="javascript:void(0);">Last Month</a>
                                <a class="dropdown-item" href="javascript:void(0);">Last Year</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <img class="img-fluid" src="{% static 'img/banner_important_task.jpg' %}" alt="Card image cap">
            <div class="featured-date mt-n4 ms-4 bg-white rounded w-px-50 shadow text-center p-1">
                <h5 class="mb-0 text-dark">21</h5>
                <span class="text-primary">May</span>
            </div>
            <div class="card-body">
                <h5 class="text-truncate">Titulo de tarea</h5>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elitias sint consectetur aut adipisci similique ab tenetur blanditiis culpa assumenda.</p>
                <div class="d-flex gap-2">
                    <span class="badge bg-label-primary">Categoria</span>
                </div>
                <div class="row mt-3">
                    <div class="col-6">
                        Tiempo restante 
                        <div class="m-0 d-flex align-items-center">
                            <h5>2 Dias, 14 horas, 2</h5>
                       </div>
                    </div>
                    <div class="col-6">
                        <div class="d-flex ">
                            <button type="button" class="btn rounded-pill btn-icon btn-success ms-auto"
                            data-bs-toggle="tooltip" data-bs-offset="0,4" data-bs-placement="top" data-bs-html="true" title="" 
                            data-bs-original-title="<span>Tarea completada</span>">
                                <i class="tf-icons fas fa-check"></i>
                            </button>
                            &nbsp;
                            <button type="button" class="btn rounded-pill btn-icon btn-danger ml-1"
                            data-bs-toggle="tooltip" data-bs-offset="0,4" data-bs-placement="top" data-bs-html="true" title="" 
                            data-bs-original-title="<span>Tarea incompleta</span>">
                                <i class="tf-icons fas fa-times"></i>
                            </button>
                            &nbsp;
                            <button type="button" class="btn rounded-pill btn-icon btn-info ml-1"
                            data-bs-toggle="tooltip" data-bs-offset="0,4" data-bs-placement="top" data-bs-html="true" title="" 
                            data-bs-original-title="<span>Posponer tarea</span>">
                                <i class="tf-icons fas fa-clock"></i>
                            </button>
                            
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>
{% endblock %}

templates/layouts/footer.html
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
        <div class="mb-2 mb-md-0">
            ©
            <script>
                document.write(new Date().getFullYear());
            </script>
            - <span class="fw-bolder">RaicoDev</span>
        </div>
        <div>
            <a href="javascript:void(0)" class="footer-link me-4">Acerca de</a>
        </div>
    </div>
</footer>

templates/layouts/navbar.html
{% load static %}
<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
	<div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
		<a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
		<i class="fas fa-bars"></i>
		</a>
	</div>
	<div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
		<!--Mensajes aleatorios de sistema-->
		<div class="navbar-nav align-items-center">
			<div class="nav-item d-flex align-items-center">
				<!--Mensaje-->
				¿Que haces aqui Niurka? XD...
			</div>
		</div>
		<!--Final Mensajes aleatorios de sistema-->

		<ul class="navbar-nav flex-row align-items-center ms-auto">
			<!-- User -->
			<li class="nav-item navbar-dropdown dropdown-user dropdown">
				<a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
					<div class="avatar avatar-online">
						<img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/profile_default.png' %} {% endif %} " alt class="w-px-40  rounded-circle" />
					</div>
				</a>
				<ul class="dropdown-menu dropdown-menu-end">
					<li>
						<a class="dropdown-item" href="#">
							<div class="d-flex">
								<div class="flex-shrink-0 me-3">
									<div class="avatar avatar-online">
										<img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'img/profile_default.png' %} {% endif %} " alt class="w-px-40 rounded-circle" />
									</div>
								</div>
								<div class="flex-grow-1">
									<span class="fw-semibold d-block">
										{% if user.nick %}
											~{{ user.nick }}
										{% else %}
											{{ user.username }}
										{% endif %}
									</span>
									<small class="text-muted">{{ user.first_name }} {{ user.last_name }}</small>
								</div>
							</div>
						</a>
					</li>
					<li>
						<div class="dropdown-divider"></div>
					</li>
					<li>
						<a class="dropdown-item" href="#">
						<i class="bx bx-user me-2"></i>
						<span class="align-middle">Mi perfil</span>
						</a>
					</li>
					<li>
						<a class="dropdown-item" href="#">
						<i class="bx bx-cog me-2"></i>
						<span class="align-middle">Ajustes</span>
						</a>
					</li>
					<li>
						<div class="dropdown-divider"></div>
					</li>
					<li>
						<a class="dropdown-item" href="{% url 'login:logOutProfile' %}">
						<i class="bx bx-power-off me-2"></i>
						<span class="align-middle">Cerrar sesion</span>
						</a>
					</li>
				</ul>
			</li>
			<!--/ User -->
		</ul>
	</div>
</nav>